# Generated by Django 4.2.2 on 2023-06-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Film Adı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('image', models.CharField(max_length=50, verbose_name='Film Posteri')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Düzenleme Tarihi')),
            ],
        ),
    ]
